src/*		                usr/share/discomp2abraflexi/
src/Discomp/*			        usr/share/discomp2abraflexi/Discomp/
debian/autoload.php             usr/share/php/SpojeNet/Discomp/
composer.json                   usr/share/php/SpojeNet/Discomp/
bin/*                           usr/bin/
example.env                     etc/discomp2abraflexi
discomp2abraflexi.svg           usr/share/icons/hicolor/scalable/apps/
io.github.spoje_net.discomp2abraflexi.metainfo.xml /usr/share/metainfo/
